import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import postcss, { type AtRule, type Root, type Rule } from "postcss";
import selectorParser, { type Node as SelectorNode, type Selector } from "postcss-selector-parser";
import tailwindcss from "tailwindcss";
import { SUI_SCOPE_CLASS } from "../src/styles/scope";
import { darkTokens, lightTokens, sharedTokens } from "../src/styles/tokens";

const require = createRequire(import.meta.url);
const tailwindConfig = require("./tailwind.internal.cjs");
const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const distDir = join(packageRoot, "dist");

const declarations = (tokens: Record<string, string>) =>
  Object.entries(tokens)
    .map(([name, value]) => `  --sui-${name}: ${value};`)
    .join("\n");

// Defaults stay in a low-priority theme layer so consumer CSS variables can override
// them cleanly. Component rules are unlayered and scoped. The package stylesheet is
// intended to load after the consumer's framework/reset stylesheet: this prevents a
// second Tailwind build from re-emitting a class such as `.px-6` after Sherick's
// responsive `.sm\\:px-7` and accidentally changing component anatomy. Consumers can
// still override an internal Tailwind utility through className because `cn()` uses
// tailwind-merge and removes the conflicting internal class from the rendered element.
const themeCss = `/* GENERATED from src/styles/tokens.ts. Do not edit this file directly. */
@layer sherick-ui-theme {
  :root,
  [data-sherick-theme="light"] {
    color-scheme: light;
${declarations(lightTokens)}
  }

  [data-sherick-theme="dark"] {
    color-scheme: dark;
${declarations(darkTokens)}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-sherick-theme]) {
      color-scheme: dark;
${declarations(darkTokens)}
    }
  }

  :root {
${declarations(sharedTokens)}
  }
}
`;

const isInsideKeyframes = (rule: Rule) => {
  let parent = rule.parent;
  while (parent) {
    if (parent.type === "atrule" && /keyframes$/i.test((parent as AtRule).name)) return true;
    parent = parent.parent;
  }
  return false;
};

const createOwnershipPseudo = () => {
  const pseudo = selectorParser.pseudo({ value: ":where" });
  const owned = selectorParser.selector();
  owned.append(selectorParser.className({ value: SUI_SCOPE_CLASS }));
  pseudo.append(owned);
  return pseudo;
};

const createDescendantScopePseudo = () => {
  const pseudo = selectorParser.pseudo({ value: ":where" });
  const self = selectorParser.selector();
  self.append(selectorParser.className({ value: SUI_SCOPE_CLASS }));
  const descendant = selectorParser.selector();
  descendant.append(selectorParser.className({ value: SUI_SCOPE_CLASS }));
  descendant.append(selectorParser.combinator({ value: " " }));
  descendant.append(selectorParser.universal());
  pseudo.append(self);
  pseudo.append(descendant);
  return pseudo;
};

const markOwnedClassCompounds = (selector: Selector) => {
  const compounds: SelectorNode[][] = [];
  let compound: SelectorNode[] = [];

  for (const node of [...selector.nodes]) {
    if (node.type === "combinator") {
      if (compound.length > 0) compounds.push(compound);
      compound = [];
      continue;
    }
    compound.push(node);
  }
  if (compound.length > 0) compounds.push(compound);

  for (const nodes of compounds) {
    if (!nodes.some((node) => node.type === "class")) continue;
    const first = nodes[0];
    first.parent?.insertBefore(first, createOwnershipPseudo());
  }
};

// Tailwind utilities are generic class names. They may only style an element that
// explicitly carries Sherick's private ownership marker. We intentionally do not use
// descendant scoping here: consumer-provided children inside Button/Card/etc. must not
// inherit Sherick's `.absolute`, `.flex`, `.text-sm`, or any other utility merely by
// living beneath a Sherick component.
const scopeUtilityRoot = (root: Root) => {
  root.walkRules((rule) => {
    if (isInsideKeyframes(rule)) return;
    rule.selector = selectorParser((selectors) => {
      selectors.each(markOwnedClassCompounds);
    }).processSync(rule.selector);
  });
  return root;
};

// KaTeX owns a namespaced subtree generated by rehype-katex and cannot receive
// `.sui-scope` on every generated descendant. Its class names are third-party-specific,
// not generic utilities, so descendant scoping is safe and intentionally limited to
// this rich-content stylesheet.
const scopeNamespacedRichContentRoot = (root: Root) => {
  root.walkRules((rule) => {
    if (isInsideKeyframes(rule)) return;
    rule.selector = selectorParser((selectors) => {
      selectors.each((selector) => selector.prepend(createDescendantScopePseudo()));
    }).processSync(rule.selector);
  });
  return root;
};

const tailwindResult = await postcss([tailwindcss(tailwindConfig)]).process("@tailwind utilities;", {
  from: join(packageRoot, "src", "styles", "generated.css"),
});
const componentRoot = scopeUtilityRoot(postcss.parse(tailwindResult.css));

const katexPath = require.resolve("katex/dist/katex.min.css");
const katexRoot = postcss.parse(await readFile(katexPath, "utf8"));
// KaTeX still ships an obsolete IE/Edge legacy high-contrast override as !important.
// Sherick provides a modern forced-colors contract below, so the legacy declaration is
// intentionally dropped rather than weakening the package-wide no-!important invariant.
katexRoot.walkDecls("-ms-high-contrast-adjust", (declaration) => declaration.remove());
// KaTeX also resets its equation counters on `body`. Package CSS may not mutate the
// consumer document globally, so make that reset local to each Sherick-owned subtree.
katexRoot.walkRules((rule) => {
  if (rule.selector === "body") rule.selector = `.${SUI_SCOPE_CLASS}`;
});
scopeNamespacedRichContentRoot(katexRoot);
const fontFaces: AtRule[] = [];
katexRoot.walkAtRules("font-face", (rule) => {
  fontFaces.push(rule.clone());
  rule.remove();
});

// Tailwind utilities such as box-shadow, ring, transform and backdrop-filter rely on
// internal custom properties that are normally initialized by Tailwind preflight.
// Sherick deliberately does not ship preflight, so initialize only those plumbing
// variables on explicitly owned Sherick nodes. Consumer descendants are untouched.
const tailwindRuntimeDefaults = `:where(.${SUI_SCOPE_CLASS}) {
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  --tw-skew-y: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
  --tw-ring-inset: ;
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgb(59 130 246 / 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  --tw-shadow-colored: 0 0 #0000;
  --tw-blur: ;
  --tw-brightness: ;
  --tw-contrast: ;
  --tw-grayscale: ;
  --tw-hue-rotate: ;
  --tw-invert: ;
  --tw-saturate: ;
  --tw-sepia: ;
  --tw-drop-shadow: ;
  --tw-backdrop-blur: ;
  --tw-backdrop-brightness: ;
  --tw-backdrop-contrast: ;
  --tw-backdrop-grayscale: ;
  --tw-backdrop-hue-rotate: ;
  --tw-backdrop-invert: ;
  --tw-backdrop-opacity: ;
  --tw-backdrop-saturate: ;
  --tw-backdrop-sepia: ;
}`;

const output = postcss.root();
for (const fontFace of fontFaces) output.append(fontFace);
output.append(postcss.parse(themeCss).nodes);
output.append(postcss.parse(tailwindRuntimeDefaults).nodes);
// Scoped component and rich-content rules intentionally remain unlayered. Loading the
// package stylesheet after host/framework CSS means both host preflight and duplicate
// host Tailwind utility definitions are settled before Sherick's internal utility graph.
output.append(...componentRoot.nodes.map((node) => node.clone()));
output.append(...katexRoot.nodes.map((node) => node.clone()));
output.append(
  postcss.parse(`@media (forced-colors: active) {

  /* A dialog and an alert dialog both separate from the page by their sheet and their shadow,
     and forced colors removes both. The alert dialog is a different role, not a different
     surface, so it needs the same boundary. */
  :where(.${SUI_SCOPE_CLASS})[role="dialog"],
  :where(.${SUI_SCOPE_CLASS})[role="alertdialog"] {
    border: 1px solid CanvasText;
  }

  /* A control whose selection is carried by tone or depth alone needs a boundary once forced
     colors flattens both: a checked switch, checkbox or radio, the selected tab, and a pressed
     toggle button — a chip or a segment. */
  :where(.${SUI_SCOPE_CLASS})[role="switch"][aria-checked="true"],
  :where(.${SUI_SCOPE_CLASS})[role="tab"][aria-selected="true"],
  :where(.${SUI_SCOPE_CLASS})[role="checkbox"][aria-checked="true"],
  :where(.${SUI_SCOPE_CLASS})[role="checkbox"][aria-checked="mixed"],
  :where(.${SUI_SCOPE_CLASS})[role="radio"][aria-checked="true"],
  :where(.${SUI_SCOPE_CLASS})[aria-pressed="true"] {
    outline: 1px solid Highlight;
    outline-offset: -2px;
  }

  /* A slider conveys its value through the fill of its groove and the depth of its handle, and
     forced colors flattens both. The handle carries a Sherick-owned marker, because Base's
     collection attributes are not component identity. */
  :where(.${SUI_SCOPE_CLASS})[data-sui-slider-thumb] {
    border: 1px solid CanvasText;
  }

  /* A progress bar says how far along the work is through the fill of its track alone, and
     forced colors flattens the fill into the track. The indicator carries a Sherick-owned marker
     for the same reason the slider thumb does: a primitive's own attributes are not component
     identity. */
  :where(.${SUI_SCOPE_CLASS})[data-sui-progress-indicator] {
    border: 1px solid CanvasText;
  }

  /* Last, because it has to win. It shares its specificity with the selected-state outlines
     above — a :where() wrapper contributes nothing, and a pseudo-class and an attribute
     selector are worth the same — so the later declaration is the one that applies. Focus is the
     transient state and the one a keyboard user cannot afford to lose: a focused control shows
     the focus ring, and the boundary that marks its selection returns when focus moves on. */
  :where(.${SUI_SCOPE_CLASS}):focus-visible {
    outline: 2px solid Highlight;
    outline-offset: 2px;
  }
}`).nodes
);

output.walkDecls((declaration) => {
  if (declaration.important) {
    throw new Error(`styles.css may not contain !important: ${declaration.toString()}`);
  }
});

await mkdir(distDir, { recursive: true });
await writeFile(join(distDir, "theme.css"), `${themeCss}\n`);
await writeFile(
  join(distDir, "styles.css"),
  `/* GENERATED by scripts/build-styles.ts. Import this file for the complete Sherick UI visual implementation. */\n${output.toString()}\n`
);

const katexDist = dirname(katexPath);
await cp(join(katexDist, "fonts"), join(distDir, "fonts"), { recursive: true });

console.log(`Built scoped Sherick UI CSS with explicit ownership marker .${SUI_SCOPE_CLASS}`);
