import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import postcss, { type AtRule, type Root, type Rule } from "postcss";
import selectorParser from "postcss-selector-parser";
import tailwindcss from "tailwindcss";
import { SUI_SCOPE_CLASS } from "../src/styles/scope";
import { darkTokens, lightTokens, sharedTokens } from "../src/styles/tokens";

const require = createRequire(import.meta.url);
const tailwindConfig = require("./tailwind.internal.cjs");
const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const distDir = join(packageRoot, "dist");

const declarations = (tokens: Record<string, string>) =>
  Object.entries(tokens)
    .map(([name, value]) => `  --sui-${name}: ${value};`)
    .join("\n");

// Defaults stay in a low-priority theme layer so ordinary consumer CSS variables can
// override them without specificity games. Component rules themselves deliberately do
// NOT live in a cascade layer: layered author rules lose to any unlayered consumer
// preflight/reset before specificity is even considered, which can erase borders,
// backgrounds and shadows. Scoping gives us isolation; normal cascade + source order
// gives consumers predictable className overrides.
const themeCss = `/* GENERATED from src/styles/tokens.ts. Do not edit this file directly. */
@layer sherick-ui-theme {
  :root,
  [data-sherick-theme="light"] {
    color-scheme: light;
${declarations(lightTokens)}
  }

  [data-sherick-theme="dark"] {
    color-scheme: dark;
${declarations(darkTokens)}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-sherick-theme]) {
      color-scheme: dark;
${declarations(darkTokens)}
    }
  }

  :root {
${declarations(sharedTokens)}
  }
}
`;

const isInsideKeyframes = (rule: Rule) => {
  let parent = rule.parent;
  while (parent) {
    if (parent.type === "atrule" && /keyframes$/i.test((parent as AtRule).name)) return true;
    parent = parent.parent;
  }
  return false;
};

const createScopePseudo = () => {
  const pseudo = selectorParser.pseudo({ value: ":where" });
  const self = selectorParser.selector();
  self.append(selectorParser.className({ value: SUI_SCOPE_CLASS }));
  const descendant = selectorParser.selector();
  descendant.append(selectorParser.className({ value: SUI_SCOPE_CLASS }));
  descendant.append(selectorParser.combinator({ value: " " }));
  descendant.append(selectorParser.universal());
  pseudo.append(self);
  pseudo.append(descendant);
  return pseudo;
};

const scopeRoot = (root: Root) => {
  root.walkRules((rule) => {
    if (isInsideKeyframes(rule)) return;
    rule.selector = selectorParser((selectors) => {
      selectors.each((selector) => selector.prepend(createScopePseudo()));
    }).processSync(rule.selector);
  });
  return root;
};

const tailwindResult = await postcss([tailwindcss(tailwindConfig)]).process("@tailwind utilities;", {
  from: join(packageRoot, "src", "styles", "generated.css"),
});
const componentRoot = scopeRoot(postcss.parse(tailwindResult.css));

const katexPath = require.resolve("katex/dist/katex.min.css");
const katexRoot = postcss.parse(await readFile(katexPath, "utf8"));
// KaTeX still ships an obsolete IE/Edge legacy high-contrast override as !important.
// Sherick provides a modern forced-colors contract below, so the legacy declaration is
// intentionally dropped rather than weakening the package-wide no-!important invariant.
katexRoot.walkDecls("-ms-high-contrast-adjust", (declaration) => declaration.remove());
// KaTeX also resets its equation counters on `body`. Package CSS may not mutate the
// consumer document globally, so make that reset local to each Sherick-owned subtree.
katexRoot.walkRules((rule) => {
  if (rule.selector === "body") rule.selector = `.${SUI_SCOPE_CLASS}`;
});
scopeRoot(katexRoot);
const fontFaces: AtRule[] = [];
katexRoot.walkAtRules("font-face", (rule) => {
  fontFaces.push(rule.clone());
  rule.remove();
});

const output = postcss.root();
for (const fontFace of fontFaces) output.append(fontFace);
output.append(postcss.parse(themeCss).nodes);
// Keep scoped component and rich-content rules unlayered. This is load-bearing: a host
// Tailwind/preflight stylesheet is also unlayered, and package component classes must
// beat low-specificity resets while still allowing later consumer utility classes to
// override equal-specificity Sherick rules intentionally.
output.append(...componentRoot.nodes.map((node) => node.clone()));
output.append(...katexRoot.nodes.map((node) => node.clone()));
output.append(
  postcss.parse(`@media (forced-colors: active) {
  :where(.${SUI_SCOPE_CLASS}, .${SUI_SCOPE_CLASS} *):focus-visible {
    outline: 2px solid Highlight;
    outline-offset: 2px;
  }

  :where(.${SUI_SCOPE_CLASS}, .${SUI_SCOPE_CLASS} *)[role="dialog"] {
    border: 1px solid CanvasText;
  }

  :where(.${SUI_SCOPE_CLASS}, .${SUI_SCOPE_CLASS} *)[role="switch"][aria-checked="true"],
  :where(.${SUI_SCOPE_CLASS}, .${SUI_SCOPE_CLASS} *)[role="tab"][aria-selected="true"] {
    outline: 1px solid Highlight;
    outline-offset: -2px;
  }
}`).nodes
);

output.walkDecls((declaration) => {
  if (declaration.important) {
    throw new Error(`styles.css may not contain !important: ${declaration.toString()}`);
  }
});

await mkdir(distDir, { recursive: true });
await writeFile(join(distDir, "theme.css"), `${themeCss}\n`);
await writeFile(
  join(distDir, "styles.css"),
  `/* GENERATED by scripts/build-styles.ts. Import this file for the complete Sherick UI visual implementation. */\n${output.toString()}\n`
);

const katexDist = dirname(katexPath);
await cp(join(katexDist, "fonts"), join(distDir, "fonts"), { recursive: true });

console.log(`Built scoped Sherick UI CSS with scope .${SUI_SCOPE_CLASS}`);
